spring.application.name=RegistryService

# Connessione al database
spring.datasource.url=jdbc:Mysql://localhost:3306/registry
spring.datasource.username=emergency
spring.datasource.password=Emergency123456@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dialect (opzionale nelle versioni recenti di Spring Boot/Hibernate)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081
server.servlet.context-path=/api

# --- TRACCIAMENTO RICHIESTE IN INGRESSO (Ricevute dai Controller) ---
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# --- TRACCIAMENTO RICHIESTE IN USCITA (Effettuate dal RestClient) ---
logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.springframework.http.client=TRACE