spring.application.name=RegistryService

# Connessione al database
spring.datasource.url=jdbc:Mysql://localhost:3306/registry
spring.datasource.username=emergency
spring.datasource.password=Emergency123456@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dialect (opzionale nelle versioni recenti di Spring Boot/Hibernate)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server configuration
server.port=8080
server.servlet.context-path=/api