apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-service
  namespace: assd-orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-service
  template:
    metadata:
      labels:
        app: operator-service
    spec:
      containers:
        - name: operator-service
          image: khondor/operator-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: emergency-config
            - secretRef:
                name: emergency-secrets
          ports:
            - containerPort: 8087
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: operator-service
  namespace: assd-orchestration
spec:
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: operator-service
