FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -pl OrchestratorService -am -DskipTests
RUN mvn clean package -pl BinderService -am -DskipTests

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/OrchestratorService/target/*.jar orchestrator.jar
COPY --from=build /app/BinderService/target/*.jar binder.jar

# Copy BPMN files
COPY --from=build /app/OrchestratorService/src/main/resources/*.bpmn /app/bpmns/

EXPOSE 8083 8082

CMD java -jar binder.jar & java -jar orchestrator.jar && wait
