apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: assd-orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: khondor/gateway-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: emergency-config
            - secretRef:
                name: emergency-secrets
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: assd-orchestration
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: gateway-service
