apiVersion: v1
kind: Secret
metadata:
  name: emergency-secrets
  namespace: assd-orchestration
type: Opaque
stringData:
  DB_USERNAME: emergency
  DB_PASSWORD: Emergency123456@
  DB_ROOT_PASSWORD: root
  JWT_SECRET: CVStBSMFRzVOozs1qq6Iefmel9cNOfWfh1OxuHW6dDB
