server.address=0.0.0.0
server.port=8080
spring.application.name=gateway
spring.threads.virtual.enabled=true

jwt.secret=CVStBSMFRzVOozs1qq6Iefmel9cNOfWfh1OxuHW6dDB
jwt.expiration=3600000

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.http.server.reactive=INFO
logging.level.reactor.netty=INFO
logging.level.reactor.netty.http.client=ERROR

reactor.netty.http.server.accessLogEnabled=true
logging.level.reactor.netty.http.server.AccessLog=INFO
