apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: assd-orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: khondor/auth-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: emergency-config
            - secretRef:
                name: emergency-secrets
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: assd-orchestration
spec:
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: auth-service
