spring.application.name=emergencies

# Connessione al database
spring.datasource.url=jdbc:Mysql://localhost:3306/registry
spring.datasource.username=emergency
spring.datasource.password=Emergency123456@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dialect (opzionale nelle versioni recenti di Spring Boot/Hibernate)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8084
server.servlet.context-path=/api

# --- KAFKA CONSUMER CONFIGURATION ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=gse-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Istruisce Jackson su quale classe usare per mappare il JSON in ingresso
spring.kafka.properties.spring.json.trusted.packages=com.unisannio.emergency.emergencies.model
spring.kafka.properties.spring.json.value.default.type=com.unisannio.emergency.emergencies.model.IncomingEventDto

# --- FEIGN CLIENT CONFIGURATION ---
# Sostituisci la porta 8081 con quella effettiva del microservizio Orchestratore
orchestrator.url=http://localhost:8083

# Abilita il log di debug per il pacchetto dei client Feign
logging.level.com.unisannio.emergency.emergencies.client=DEBUG

# Abilita il logger di Feign per vedere i dettagli delle chiamate HTTP (HEADERS, FULL, BASIC, NONE)
logging.level.org.springframework.cloud.openfeign=DEBUG

# --- TRACCIAMENTO RICHIESTE IN INGRESSO (Ricevute dai Controller) ---
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# --- TRACCIAMENTO RICHIESTE IN USCITA (Effettuate dal RestClient) ---
logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.springframework.http.client=TRACE