spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.application.name=operator-service
server.port=8087

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/operator_db?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.web=INFO
logging.level.com.spendy.operator=DEBUG

# Tracciamento delle richieste in ingresso (Ricevute dai Controller del Binder)
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Tracciamento delle chiamate in uscita (Effettuate dal Binder verso il Registro)
logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.springframework.http.client=TRACE

auth.service.url=${GATEWAY_URL}/api/auth
escalation.webhook.base-url=${ESCALATION_WEBHOOK_URL}