spring.application.name=auth-service
spring.datasource.url=jdbc:mysql://localhost:3306/registry
spring.datasource.username=emergency
spring.datasource.password=Emergency123456@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8086
logging.level.org.springframework.security=DEBUG

