spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.application.name=auth-service
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/auth_db?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8088
logging.level.org.springframework.security=DEBUG

gateway.generate-token.url=${GATEWAY_URL}/gateway/generate-token
gateway.verify-token.url=${GATEWAY_URL}/gateway/verify-token
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
